service: slack-showtimes

provider:
  name: aws
  runtime: java8
  region: us-west-2
  stage: dev
  profile: serverless
  timeout: 10
  environment:
    TMS_API_KEY: ${file(creds.yaml):TMS_API_KEY}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject*"
        - "s3:GetObject*"
      Resource: "arn:aws:s3:::movie-showtimes/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::movie-showtimes"


package:
  artifact: target/scala-2.12/movie-scraping-api.jar

functions:
  loadcache:
    timeout: 20
    handler: me.chadrs.CacheTasks::loadCache
    events:
      - schedule: rate(4 hours)
  api:
    handler: me.chadrs.Launch$EntryPoint::handle
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true